# Generated by Django 2.1 on 2019-07-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=22)),
                ('p_date', models.DateField()),
                ('prize', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
            options={
                'db_table': 'Laptop_info',
            },
        ),
    ]
